/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
  'dueAmount' : IDL.Float64,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const InvoiceItem = IDL.Record({
  'qty' : IDL.Nat,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'unitPrice' : IDL.Float64,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Float64,
  'date' : IDL.Int,
  'invoiceNumber' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(InvoiceItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'barcode' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'invoiceId' : IDL.Nat,
  'customerId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Settings = IDL.Record({
  'ownerName' : IDL.Text,
  'businessName' : IDL.Text,
  'logoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], []),
  'createExpense' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [Expense], []),
  'createInvoice' : IDL.Func(
      [IDL.Nat, IDL.Vec(InvoiceItem), IDL.Float64, IDL.Text],
      [Invoice],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Product],
      [],
    ),
  'createSale' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [Sale], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalSalesAmount' : IDL.Float64,
          'todayRevenue' : IDL.Float64,
          'totalCustomers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getExpensesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getExpensesByMonth' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProfitLoss' : IDL.Func(
      [IDL.Int, IDL.Int],
      [
        IDL.Record({
          'expenses' : IDL.Float64,
          'sales' : IDL.Float64,
          'profit' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getTotalSales' : IDL.Func([IDL.Int, IDL.Int], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [Customer],
      [],
    ),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
      [Expense],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Product],
      [],
    ),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
    'dueAmount' : IDL.Float64,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const InvoiceItem = IDL.Record({
    'qty' : IDL.Nat,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'unitPrice' : IDL.Float64,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Float64,
    'date' : IDL.Int,
    'invoiceNumber' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(InvoiceItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'barcode' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'invoiceId' : IDL.Nat,
    'customerId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Settings = IDL.Record({
    'ownerName' : IDL.Text,
    'businessName' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], []),
    'createExpense' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [Expense],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Nat, IDL.Vec(InvoiceItem), IDL.Float64, IDL.Text],
        [Invoice],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Product],
        [],
      ),
    'createSale' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [Sale], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalSalesAmount' : IDL.Float64,
            'todayRevenue' : IDL.Float64,
            'totalCustomers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByMonth' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProfitLoss' : IDL.Func(
        [IDL.Int, IDL.Int],
        [
          IDL.Record({
            'expenses' : IDL.Float64,
            'sales' : IDL.Float64,
            'profit' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getTotalSales' : IDL.Func([IDL.Int, IDL.Int], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [Customer],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
        [Expense],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Product],
        [],
      ),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };