/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
  'dueAmount' : number,
}
export interface Expense {
  'id' : bigint,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface Invoice {
  'id' : bigint,
  'total' : number,
  'date' : bigint,
  'invoiceNumber' : string,
  'notes' : string,
  'customerId' : bigint,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem {
  'qty' : bigint,
  'productId' : bigint,
  'productName' : string,
  'unitPrice' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'unit' : string,
  'description' : string,
  'imageUrl' : string,
  'barcode' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : number,
}
export interface Sale {
  'id' : bigint,
  'date' : bigint,
  'invoiceId' : bigint,
  'customerId' : bigint,
  'amount' : number,
}
export interface Settings {
  'ownerName' : string,
  'businessName' : string,
  'logoUrl' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<[string, string], Customer>,
  'createExpense' : ActorMethod<[number, string, string], Expense>,
  'createInvoice' : ActorMethod<
    [bigint, Array<InvoiceItem>, number, string],
    Invoice
  >,
  'createProduct' : ActorMethod<
    [string, number, bigint, string, string, string, string, string],
    Product
  >,
  'createSale' : ActorMethod<[bigint, bigint, number], Sale>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalSalesAmount' : number,
      'todayRevenue' : number,
      'totalCustomers' : bigint,
    }
  >,
  'getExpensesByCategory' : ActorMethod<[string], Array<Expense>>,
  'getExpensesByMonth' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProfitLoss' : ActorMethod<
    [bigint, bigint],
    { 'expenses' : number, 'sales' : number, 'profit' : number }
  >,
  'getSettings' : ActorMethod<[], Settings>,
  'getTotalSales' : ActorMethod<[bigint, bigint], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<[bigint, string, string, number], Customer>,
  'updateExpense' : ActorMethod<[bigint, number, string, string], Expense>,
  'updateProduct' : ActorMethod<
    [bigint, string, number, bigint, string, string, string, string, string],
    Product
  >,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];